const SHOP_DATA = {
  damas: {
    id: 1,
    title: "Damas",
    routeName: "damas",
    items: [
      {
        id: 1,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/B22kcRN/IMG-1070.jpg",
        price: 16,
      },
      {
        id: 2,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/B22kcRN/IMG-1070.jpg",
        price: 17,
      },
      {
        id: 3,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/B22kcRN/IMG-1070.jpg",
        price: 18,
      },
      {
        id: 4,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/B22kcRN/IMG-1070.jpg",
        price: 20,
      },
      {
        id: 5,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/rpQ3wMW/IMG-1069.jpg",
        price: 16,
      },
      {
        id: 6,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/rpQ3wMW/IMG-1069.jpg",
        price: 17,
      },
      {
        id: 7,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/rpQ3wMW/IMG-1069.jpg",
        price: 18,
      },
      {
        id: 8,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/rpQ3wMW/IMG-1069.jpg",
        price: 20,
      },
      {
        id: 9,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/fHnW7X5/IMG-1067.jpg",
        price: 16,
      },
      {
        id: 10,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/fHnW7X5/IMG-1067.jpg",
        price: 17,
      },
      {
        id: 11,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/fHnW7X5/IMG-1067.jpg",
        price: 18,
      },
      {
        id: 12,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/fHnW7X5/IMG-1067.jpg",
        price: 20,
      },
      {
        id: 13,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/vvqPs0R/IMG-1068.jpg",
        price: 16,
      },
      {
        id: 14,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/vvqPs0R/IMG-1068.jpg",
        price: 17,
      },
      {
        id: 15,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/vvqPs0R/IMG-1068.jpg",
        price: 18,
      },
      {
        id: 16,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/vvqPs0R/IMG-1068.jpg",
        price: 20,
      },
      {
        id: 21,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/hXjsR1L/IMG-0603.jpg",
        price: 16,
      },
      {
        id: 22,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/hXjsR1L/IMG-0603.jpg",
        price: 17,
      },
      {
        id: 23,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/hXjsR1L/IMG-0603.jpg",
        price: 18,
      },
      {
        id: 24,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/hXjsR1L/IMG-0603.jpg",
        price: 20,
      },
      {
        id: 25,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/1q5Shhz/IMG-0602.jpg",
        price: 16,
      },
      {
        id: 26,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/1q5Shhz/IMG-0602.jpg",
        price: 17,
      },
      {
        id: 27,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/1q5Shhz/IMG-0602.jpg",
        price: 18,
      },
      {
        id: 28,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/1q5Shhz/IMG-0602.jpg",
        price: 20,
      },
      {
        id: 29,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/rH6spXs/IMG-0601.jpg",
        price: 16,
      },
      {
        id: 30,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/rH6spXs/IMG-0601.jpg",
        price: 17,
      },
      {
        id: 31,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/rH6spXs/IMG-0601.jpg",
        price: 18,
      },
      {
        id: 32,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/rH6spXs/IMG-0601.jpg",
        price: 20,
      },
      {
        id: 33,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/YtbZqQZ/IMG-0600.jpg",
        price: 16,
      },
      {
        id: 34,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/YtbZqQZ/IMG-0600.jpg",
        price: 17,
      },
      {
        id: 35,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/YtbZqQZ/IMG-0600.jpg",
        price: 18,
      },
      {
        id: 36,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/YtbZqQZ/IMG-0600.jpg",
        price: 20,
      },
      {
        id: 37,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/w09dVpM/IMG-0597.jpg",
        price: 16,
      },
      {
        id: 38,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/w09dVpM/IMG-0597.jpg",
        price: 17,
      },
      {
        id: 39,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/w09dVpM/IMG-0597.jpg",
        price: 18,
      },
      {
        id: 40,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/w09dVpM/IMG-0597.jpg",
        price: 20,
      },
      {
        id: 41,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/QvTc1kJ/IMG-1080.jpg",
        price: 14,
      },
      {
        id: 42,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/QvTc1kJ/IMG-1080.jpg",
        price: 14,
      },
      {
        id: 43,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/QvTc1kJ/IMG-1080.jpg",
        price: 15,
      },
      {
        id: 44,
        name: "Polo de Manga corta - Talla XL",
        imageUrl: "https://i.ibb.co/QvTc1kJ/IMG-1080.jpg",
        price: 16,
      },
      {
        id: 45,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/bW1Fy65/IMG-1079.jpg",
        price: 14,
      },
      {
        id: 46,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/bW1Fy65/IMG-1079.jpg",
        price: 14,
      },
      {
        id: 47,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/bW1Fy65/IMG-1079.jpg",
        price: 15,
      },
      {
        id: 48,
        name: "Polo de Manga corta - Talla XL",
        imageUrl: "https://i.ibb.co/bW1Fy65/IMG-1079.jpg",
        price: 16,
      },
      {
        id: 17,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/SxdgmCZ/IMG-0609.jpg",
        price: 14,
      },
      {
        id: 18,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/SxdgmCZ/IMG-0609.jpg",
        price: 14,
      },
      {
        id: 19,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/SxdgmCZ/IMG-0609.jpg",
        price: 15,
      },
      {
        id: 20,
        name: "Polo de Manga corta - Talla XL",
        imageUrl: "https://i.ibb.co/SxdgmCZ/IMG-0609.jpg",
        price: 16,
      },
      {
        id: 49,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/4K6FpwL/IMG-1078.jpg",
        price: 14,
      },
      {
        id: 59,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/4K6FpwL/IMG-1078.jpg",
        price: 14,
      },
      {
        id: 51,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/4K6FpwL/IMG-1078.jpg",
        price: 15,
      },
      {
        id: 52,
        name: "Polo de Manga corta - Talla XL",
        imageUrl: "https://i.ibb.co/4K6FpwL/IMG-1078.jpg",
        price: 16,
      },
      {
        id: 53,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/Vg9g9Vc/IMG-1077.jpg",
        price: 14,
      },
      {
        id: 54,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/Vg9g9Vc/IMG-1077.jpg",
        price: 14,
      },
      {
        id: 55,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/Vg9g9Vc/IMG-1077.jpg",
        price: 15,
      },
      {
        id: 56,
        name: "Polo de Manga corta - Talla XL",
        imageUrl: "https://i.ibb.co/Vg9g9Vc/IMG-1077.jpg",
        price: 16,
      },
    ],
  },
  caballeros: {
    id: 2,
    title: "Caballeros",
    routeName: "caballeros",
    items: [
      {
        id: 57,
        name: "Polo de Manga larga- Talla S",
        imageUrl: "https://i.ibb.co/wc1nFF3/IMG-1072.jpg",
        price: 22,
      },
      {
        id: 58,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/wc1nFF3/IMG-1072.jpg",
        price: 23,
      },
      {
        id: 59,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/wc1nFF3/IMG-1072.jpg",
        price: 24,
      },
      {
        id: 61,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/5sZMXqg/IMG-1071.jpg",
        price: 22,
      },
      {
        id: 62,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/5sZMXqg/IMG-1071.jpg",
        price: 23,
      },
      {
        id: 63,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/5sZMXqg/IMG-1071.jpg",
        price: 24,
      },
      {
        id: 65,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/q53HYXR/IMG-0608.jpg",
        price: 22,
      },
      {
        id: 66,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/q53HYXR/IMG-0608.jpg",
        price: 23,
      },
      {
        id: 67,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/q53HYXR/IMG-0608.jpg",
        price: 24,
      },
      {
        id: 68,
        name: "Polo de Manga corta - Talla S",
        imageUrl:
          "https://i.ibb.co/YQN5N8g/114485521-609727476612671-8872437776035317934-n.jpg",
        price: 17,
      },
      {
        id: 69,
        name: "Polo de Manga corta - Talla M",
        imageUrl:
          "https://i.ibb.co/YQN5N8g/114485521-609727476612671-8872437776035317934-n.jpg",
        price: 18,
      },
      {
        id: 70,
        name: "Polo de Manga corta - Talla L",
        imageUrl:
          "https://i.ibb.co/YQN5N8g/114485521-609727476612671-8872437776035317934-n.jpg",
        price: 19,
      },
      {
        id: 71,
        name: "Polo de Manga corta - Talla S",
        imageUrl:
          "https://i.ibb.co/1rLpbj2/109804997-738993296888529-4828653987521850219-n.jpg",
        price: 17,
      },
      {
        id: 72,
        name: "Polo de Manga corta - Talla M",
        imageUrl:
          "https://i.ibb.co/1rLpbj2/109804997-738993296888529-4828653987521850219-n.jpg",
        price: 18,
      },
      {
        id: 73,
        name: "Polo de Manga corta - Talla L",
        imageUrl:
          "https://i.ibb.co/1rLpbj2/109804997-738993296888529-4828653987521850219-n.jpg",
        price: 19,
      },
      {
        id: 74,
        name: "Polo de Manga corta - Talla S",
        imageUrl:
          "https://i.ibb.co/100v1tY/115821669-1406231966213999-1413138122468113182-n.jpg",
        price: 17,
      },
      {
        id: 75,
        name: "Polo de Manga corta - Talla M",
        imageUrl:
          "https://i.ibb.co/100v1tY/115821669-1406231966213999-1413138122468113182-n.jpg",
        price: 18,
      },
      {
        id: 76,
        name: "Polo de Manga corta - Talla L",
        imageUrl:
          "https://i.ibb.co/100v1tY/115821669-1406231966213999-1413138122468113182-n.jpg",
        price: 19,
      },
      {
        id: 77,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/3B1sSQb/Polo-negro-hombre.jpg",
        price: 17,
      },
      {
        id: 78,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/3B1sSQb/Polo-negro-hombre.jpg",
        price: 18,
      },
      {
        id: 79,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/3B1sSQb/Polo-negro-hombre.jpg",
        price: 19,
      },
      {
        id: 782,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/GtDxWSD/polo-hombre-rojo01.jpg",
        price: 17,
      },
      {
        id: 792,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/GtDxWSD/polo-hombre-rojo01.jpg",
        price: 18,
      },
      {
        id: 80,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/GtDxWSD/polo-hombre-rojo01.jpg",
        price: 19,
      },
      {
        id: 81,
        name: "Polo de Manga corta - Talla S",
        imageUrl:
          "https://i.ibb.co/CzKR4W9/3b158a3671b6ad3dbb2f2fcc6fefc662-product.jpg",
        price: 17,
      },
      {
        id: 82,
        name: "Polo de Manga corta - Talla M",
        imageUrl:
          "https://i.ibb.co/CzKR4W9/3b158a3671b6ad3dbb2f2fcc6fefc662-product.jpg",
        price: 18,
      },
      {
        id: 83,
        name: "Polo de Manga corta - Talla L",
        imageUrl:
          "https://i.ibb.co/CzKR4W9/3b158a3671b6ad3dbb2f2fcc6fefc662-product.jpg",
        price: 19,
      },
      {
        id: 84,
        name: "Polo de Manga corta - Talla S",
        imageUrl: "https://i.ibb.co/KFZMcTC/verdemilitar01.jpg",
        price: 17,
      },
      {
        id: 85,
        name: "Polo de Manga corta - Talla M",
        imageUrl: "https://i.ibb.co/KFZMcTC/verdemilitar01.jpg",
        price: 18,
      },
      {
        id: 86,
        name: "Polo de Manga corta - Talla L",
        imageUrl: "https://i.ibb.co/KFZMcTC/verdemilitar01.jpg",
        price: 19,
      },
    ],
  },
  niños: {
    id: 3,
    title: "Niños",
    routeName: "niños",
    items: [
      {
        id: 87,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/2MBBz4Q/IMG-1074.jpg",
        price: 16,
      },
      {
        id: 88,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/2MBBz4Q/IMG-1074.jpg",
        price: 17,
      },
      {
        id: 89,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/2MBBz4Q/IMG-1074.jpg",
        price: 18,
      },
      {
        id: 90,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/2MBBz4Q/IMG-1074.jpg",
        price: 20,
      },
      {
        id: 91,
        name: "Polo de Manga larga - Talla S",
        imageUrl: "https://i.ibb.co/fn3NpQx/IMG-1075.jpg",
        price: 16,
      },
      {
        id: 92,
        name: "Polo de Manga larga - Talla M",
        imageUrl: "https://i.ibb.co/fn3NpQx/IMG-1075.jpg",
        price: 17,
      },
      {
        id: 93,
        name: "Polo de Manga larga - Talla L",
        imageUrl: "https://i.ibb.co/fn3NpQx/IMG-1075.jpg",
        price: 18,
      },
      {
        id: 94,
        name: "Polo de Manga larga - Talla XL",
        imageUrl: "https://i.ibb.co/fn3NpQx/IMG-1075.jpg",
        price: 20,
      },
    ],
  },
};

export default SHOP_DATA;
